<a href="https://colab.research.google.com/github/bhavanihbvb/Artificial-Intelligence/blob/main/adding_the_elements_using_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import tensorflow as tf

tensor1 = tf.constant([[1, 2, 3],
                        [4, 5, 6]])

tensor2 = tf.constant([[7, 8, 9],
                        [10, 11, 12]])

tensor_sum = tf.add(tensor1, tensor2)

print(tensor_sum)


tf.Tensor(
[[ 8 10 12]
 [14 16 18]], shape=(2, 3), dtype=int32)


In [5]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [10, 11, 12]])

C = A + B

print(C)


[[ 8 10 12]
 [14 16 18]]


In [6]:
import numpy as np

# Create two (2,3) tensors with random values
A = np.random.rand(2, 3)
B = np.random.rand(2, 3)

# Element-wise addition
C = A + B

print("Tensor A:\n", A)
print("\nTensor B:\n", B)
print("\nElement-wise Addition (A + B):\n", C)


Tensor A:
 [[0.12440618 0.97750509 0.03681593]
 [0.77648358 0.5093625  0.35559467]]

Tensor B:
 [[0.38736058 0.52620063 0.56476348]
 [0.51701334 0.36727181 0.01362989]]

Element-wise Addition (A + B):
 [[0.51176676 1.50370572 0.60157941]
 [1.29349693 0.87663432 0.36922456]]
